### Power Community Demo ###
get {{baseurl}}/api/v2.0/
Authorization: Basic {{username}} {{password}}









### Get Companies ###
# @name companies
get {{baseurl}}/api/v2.0/companies
Authorization: Basic {{username}} {{password}}










### set company Id variables ###
@companyid = {{companies.response.body.value[0].id}}

### Items ###
get {{baseurl}}/api/v2.0/companies({{companyid}})/items?$orderby= number asc
Authorization: Basic {{username}} {{password}}

#get {{baseurl}}/api/v2.0/companies({{companyid}})/items?$filter=itemCategoryCode eq 'TABLE'
#get {{baseurl}}/api/v2.0/companies({{companyid}})/items?$count=true
#get {{baseurl}}/api/v2.0/companies({{companyid}})/items?$skip=3

### Employee ###
get {{baseurl}}/api/v2.0/companies({{companyid}})/employees
Authorization: Basic {{username}} {{password}}







### Create Employee ###
post {{baseurl}}/api/v2.0/companies({{companyid}})/employees
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "surname" : "Community",
    "givenName" : "Power"
}